{block #css}
    <link type="text/css" href="{$basePath}/css/widgets/datagrid/datagrid.css" rel="stylesheet" />
{/block}
{block #js}
    <script type="text/javascript" src="{$basePath}/js/jquery-1.4.2.min.js"></script>
          <script type="text/javascript" src="{$basePath}/js/jquery-ui-1.7.2.custom.min.js"></script>
          <script type="text/javascript" src="{$basePath}/js/jquery.ajaxform.js"></script>
          <script type="text/javascript" src="{$basePath}/js/jquery.livequery.js"></script>
          <script type="text/javascript" src="{$basePath}/js/jquery.nette.js"></script>
          <script type="text/javascript" src="{$basePath}/js/effects.js"></script>
          <script type="text/javascript" src="{$basePath}/js/LiveFormValidation.js"></script>
    <script type="text/javascript" src="{$basePath}/js/widgets/datagrid/datagrid.js"></script>
{/block}
{include #content}
