{**
 * Diplomovy projekt template.
 *
 * @copyright  Copyright (c) 2009 Martin Bazik
 * @package    Skusky
 *
 * @param string   $title    page title
 * @param string   $robots   tell robots how to index the content of a page (optinal)
 * @param string   $basePath  web base URI
 * @param array    $flashes  flash messages
 * @param Template $content  view template
 *}

<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Diplomovy projekt" />
	<meta name="robots" content="NOINDEX, NOFOLLOW">

	<title>{_$module}{if isset($title)} - {_$title}{/if}</title>
  {block #css}
        <link type="text/css" href="{$basePath}/css/layout.css" rel="stylesheet" />
        <link type="text/css" href="{$basePath}/css/menu_style.css" rel="stylesheet" />
        <link type="text/css" href="{$basePath}/css/{$module|lower}/menu_style_{$module|lower}" rel="stylesheet" />
  {/block}
  {block #js}
          <script type="text/javascript" src="{$basePath}/js/LiveFormValidation.js"></script>
  {/block}
</head>
<body>
    <div id="container">
	<div id="content">
        {snippet flash}
            @{foreach $flashes as $flash}
                <div class="flash {$flash->type}">{$flash->message}</div>
            @{/foreach}
        {/snippet}
        @{include #content}
	</div>
    </div>
</body>
</html>
</body>
</html>